# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: puka
email: contact@puka.fr
description: > # this means to ignore newlines until "baseurl:"
  Avec puka, organisez vos données, en ligne. Grâce à son générateur de formulaires, puka vous permet de récolter, filtrer, trier, et gérer vos données aisément.
  Vous pouvez également importer et exporter vos données depuis et vers les formats CSV et Excel.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.puka.fr" # the base hostname & protocol for your site
host: 0.0.0.0

# Build settings
markdown: kramdown

